### ISSUE TITLE
Parâmetros extras do SDCC no arquivo de configuração

### ISSUE THREAD

**Issue by rodsiqbr** [DamnedAngel/MSX-Templates-for-VisualStudio#25]
Seria interessante adicionar no ApplicationSettings.txt um parâmetro extra que seria passado para o SDCC, incluindo outros parâmetros de compilação/link necessários para um projeto específico. Por exemplo:

SDCC_EXTRA_DIRECTIVES  "--fsigned-char --std-sdcc99 --fomit-frame-pointer"

Isso se aplicaria na linha do SDCC do Make.bat
call :exec %DBG_CALL1% sdcc --code-loc %CODE_LOC% --data-loc %DATA_LOC% -mz80 --no-std-crt0 --opt-code-size **%SDCC_EXTRA_DIRECTIVES%** --disable-warning 196 %OBJLIST% %INCDIRS% -o "%MSX_OBJ_PATH%\%MSX_FILE_NAME%.IHX"

**Comment by DamnedAngel** [comment]
IMplemented in TKT_00031.
